export const allMembers = [
	"Appalachian State University Belk Library and Information Commons",
	"Arcadia Science",
	"Belk Library & Information Commons",
	"Berlin University Alliance",
	"Bill & Melinda Gates Foundation",
	"Brown University Center for Digital Scholarship",
	"Center of Complex Inventions",
	"Centre for Applied Strength and Conditioning Science",
	"CITAP",
	"Coalition for Diversity and Inclusion in Scholarly Communications",
	"COPIM",
	"The Cuvette",
	"Criminology Open",
	"Duke Kunshan University, SciEcon CIC",
	"Eksistensen",
	"Internet of Production",
	"Invisible Culture",
	"Iowa State University Library",
	"KU Leuven Libraries",
	"Litzsinger Road Ecology Foundation",
	"Maastricht University",
	"Media Studies Press",
	"MIT Libraries",
	"MIT Press",
	"NC State University Libraries",
	"New Things Under The Sun",
	"Ocean Discovery League",
	"Open Engineering",
	"Project for Peaceful Competition",
	"punctum books",
	"San Antonio Review",
	"Society for the Anthropology of Work",
	"Sustainable Futures Lab",
	"The Children's Hospital of Philadelphia",
	"The Global Health Network, Centre for Tropical Medicine and Global Health",
	"The Open University",
	"Tilburg University",
	"University of Vermont Howe Library",
	"Vanderbilt University Jean & Alexander Heard Libraries",
	"Z. Smith Reynolds Library, Wake Forest University",
];
// export const network = ["Arcadia Science", "The MIT Press"];
// export const contributing = [
// 	"American Astronomical Society",
// 	"Appalachian State University Belk Library and Information Commons",
// 	"Berlin Exchange",
// 	"Children's Hospital of Philadelphia",
// 	"Criminology Open",
// 	"Iowa State University Library",
// 	"KU Leuven Libraries",
// 	"Media Studies Press",
// 	"MIT Libraries",
// 	"punctum books",
// 	"San Antonio Review",
// 	"The Global Health Network, Centre for Tropical Medicine and Global Health",
// 	"Tilburg University",
// 	"Vanderbilt University Jean & Alexander Heard Libraries",
// ];
// export const supporting = [
// 	"Duke Kunshan University, SciEcon CIC",
// 	"Coalition for Diversity and Inclusion in Scholarly Communications",
// 	"Internet of Production",
// 	"Invisible Culture",
// 	"Matthew E. Thrasher",
// 	"Centre for Applied Strength and Conditioning Science",
// 	"New Things Under the Sun",
// 	"Society for the Anthropology of Work",
// 	"Sustainable Futures Lab",
// 	"The Open University",
// 	"The University of Vermont Libraries",
// ];
