export const allMembers = [
	"Arcadia Science",
	"Belk Library & Information Commons",
	"Berlin University Alliance",
	"Bill & Melinda Gates Foundation",
	"Center of Complex Inventions",
	"CITAP",
	"Coalition for Diversity and Inclusion in Scholarly Communications",
	"COPIM",
	"Eksistensen",
	"Internet of Production",
	"Invisible Culture",
	"Iowa State University Library",
	"KU Leuven Libraries",
	"Litzsinger Road Ecology Foundation",
	"Maastricht University",
	"Media Studies Press",
	"MIT Libraries",
	"MIT Press",
	"NC State University Libraries",
	"Ocean Discovery League",
	"Society for the Anthropology of Work",
	"Open Engineering",
	"Project for Peaceful Competition",
	"punctum books",
	"The Children's Hospital of Philadelphia",
	"Tilburg University",
	"Appalachian State University Belk Library and Information Commons",
	"University of Vermont Howe Library",
	"Z. Smith Reynolds Library, Wake Forest University",
	"The Open University",
	"Sustainable Futures Lab",
	"New Things Under The Sun",
	"Invisible Culture",
	"Internet of Production",
	"Duke Kunshan University, SciEcon CIC",
	"Centre for Applied Strength and Conditioning Science",
	"The Global Health Network, Centre for Tropical Medicine and Global Health",
	"Vanderbilt University Jean & Alexander Heard Libraries",
	"San Antonio Review",
	"Criminology Open",
	"plus 11 individual contributors.",
];
// export const network = ["Arcadia Science", "The MIT Press"];
// export const contributing = [
// 	"American Astronomical Society",
// 	"Appalachian State University Belk Library and Information Commons",
// 	"Berlin Exchange",
// 	"Children's Hospital of Philadelphia",
// 	"Criminology Open",
// 	"Iowa State University Library",
// 	"KU Leuven Libraries",
// 	"Media Studies Press",
// 	"MIT Libraries",
// 	"punctum books",
// 	"San Antonio Review",
// 	"The Global Health Network, Centre for Tropical Medicine and Global Health",
// 	"Tilburg University",
// 	"Vanderbilt University Jean & Alexander Heard Libraries",
// ];
// export const supporting = [
// 	"Duke Kunshan University, SciEcon CIC",
// 	"Coalition for Diversity and Inclusion in Scholarly Communications",
// 	"Internet of Production",
// 	"Invisible Culture",
// 	"Matthew E. Thrasher",
// 	"Centre for Applied Strength and Conditioning Science",
// 	"New Things Under the Sun",
// 	"Society for the Anthropology of Work",
// 	"Sustainable Futures Lab",
// 	"The Open University",
// 	"The University of Vermont Libraries",
// ];
